name: BulletinBoard
description: A simple bulletin board plugin
version: '${version}'
main: net.rk4z.bulletinBoard.BulletinBoard
api-version: '1.20'
author: Ruxy
commands:
  bb:
    description: Bulletin Board command
    aliases: [bboard, bulletinboard]