name: BulletinBoard
description: A simple bulletin board plugin
version: '${version}'
main: net.rk4z.bulletinboard.BulletinBoard
api-version: '1.20'

commands:
  bb:
    description: Bulletin Board command
    aliases: [bboard, bulletinboard]